sudo: required
dist: trusty # Ubuntu 14.04
services: docker # Enables docker
script:
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
- ./latexdockercmd.sh latexmk -xelatex -pdf -outdir=./_build
env:
  global:
    - secure: "RBJDnWOtTbkAAie+D3m4mtloHgJy1En54guxQDnIlWedZe5DqB4gN/DuVRw+uOFnXREqlRyqDRyjYimzCXVX4rhLw1MTx09vcDnvKeG5DoH0SaCcfCtWjTYsR8qhk40APLXQyndIAJYj/P1agyY6FbFt2cXxZGuKdKPzc0jNt0VpDKYqgQkJrBIwd9Fyoxs7DzvLtbJw72aw1g6G4JRezgIQKOL4/8gzo2p4jDGiZf3kbmcLm7MR0ev1BQ4VHEaRzhDWG12AlpjCheyMxA5dtkFAwr+Mvrus6JX0tCOFaUv/DPt0/VD0RS+rPCXjYOLrinRbUGxsdLTyRDoRCjOfkfB7TDF2U5+yC4UUYsmonwJ96pBBgQtYm0YBEaVIrhIUDgsUWB2e+7xiBZSeq+bh2RuKvfA4x3snn3Ik65elwQ9jFSR+o5ufpiChtcmliQvGj3pyYDHYqUKHeaEfwh89jEo6jEf/KklMijvnVOabfzYecNmQ8D7sqWIiiLyN4qVNPeWalk+zDqLDCbeSVdP9WyLWgSlJx9f2oEtKa7GEi862ZT13sAk0wqSPoOPYRu19cj7xAcE2rN4wE/RCvzpACa2ZqJJRSypg2Qsy+lHJB+pggPMTMq/HOXHC5e3gonq8U+pZX+ER0OaPMJB4/7pjEr0M7ntm9jgzSmFt6Gxmmic="